# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='piyo', max_length=255, verbose_name='書籍名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.IntegerField(blank=True, default=0, verbose_name='ページ数'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default=True, max_length=255, verbose_name='出版社'),
        ),
    ]
