# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_impression'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='book',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='cms.Book', verbose_name='書籍'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impression',
            name='comment',
            field=models.TextField(blank=True, verbose_name='コメント'),
        ),
    ]
