# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170825_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='出版社'),
        ),
    ]
